version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip

      - run: echo "building"
